name: Breaking News Scraper
on:
  schedule:
    - cron: '0 */4 * * *'    # Runs every 2 hours
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  scrape-breaking-news:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch breaking news - English
        id: fetch-en
        continue-on-error: true
        timeout-minutes: 3
        run: |
          echo "Running English scraper at $(date)"
          HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" -X GET "${{ vars.APP_URL }}/api/scraper/breaking-news?locale=en")
          if [[ $HTTP_STATUS -ne 200 ]]; then
            echo "::error::Failed to scrape English news. HTTP status: $HTTP_STATUS"
            cat response.json
            exit 1
          else
            echo "English scraper completed successfully"
            cat response.json
          fi
      
      - name: Retry English scraper if failed
        if: ${{ failure() && steps.fetch-en.outcome == 'failure' }}
        timeout-minutes: 3
        run: |
          echo "Retrying English scraper at $(date)"
          curl -v -X GET "${{ vars.APP_URL }}/api/scraper/breaking-news?locale=en"
        
      - name: Fetch breaking news - Arabic
        id: fetch-ar
        continue-on-error: true
        timeout-minutes: 3
        run: |
          echo "Running Arabic scraper at $(date)"
          HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" -X GET "${{ vars.APP_URL }}/api/scraper/breaking-news?locale=ar")
          if [[ $HTTP_STATUS -ne 200 ]]; then
            echo "::error::Failed to scrape Arabic news. HTTP status: $HTTP_STATUS"
            cat response.json
            exit 1
          else
            echo "Arabic scraper completed successfully"
            cat response.json
          fi
          
      - name: Retry Arabic scraper if failed
        if: ${{ failure() && steps.fetch-ar.outcome == 'failure' }}
        timeout-minutes: 3
        run: |
          echo "Retrying Arabic scraper at $(date)"
          curl -v -X GET "${{ vars.APP_URL }}/api/scraper/breaking-news?locale=ar"